# "Basic PyTorch Functions"

- toc: true
- branch: master
- badges: true
- comments: true
- categories: [pytorch, math]
- hide: false
- author: Vinay Kudari
- search_exclude: true
- metadata_key1: pytorch

In [42]:
import torch
from torch import tensor
import torch.nn.functional as F

### Embedding

Embedding indexes into a vector using an integer, but has its derivative calculated in such a way that it is identical to what it would have been if it had done a matrix multiplication with a one-hot-encoded vector.

In [54]:
??F.embedding

In [44]:
matrix = torch.randn(5, 5)
matrix

tensor([[-0.2647, -1.9060, -0.1566,  0.3325, -0.5478],
        [-0.7716, -0.0692,  0.7523, -0.1736,  0.0876],
        [-0.6952,  0.1141,  0.2111,  0.2130, -0.6404],
        [ 0.7191,  0.4450, -0.2955, -0.8187, -0.0228],
        [-0.9783,  0.0550, -0.9054,  1.8447, -1.3366]])

In [46]:
idx = tensor([[1, 2, 2], [2, 3, 4]])
idx

tensor([[1, 2, 2],
        [2, 3, 4]])

In [47]:
F.embedding(idx, matrix)

tensor([[[-0.7716, -0.0692,  0.7523, -0.1736,  0.0876],
         [-0.6952,  0.1141,  0.2111,  0.2130, -0.6404],
         [-0.6952,  0.1141,  0.2111,  0.2130, -0.6404]],

        [[-0.6952,  0.1141,  0.2111,  0.2130, -0.6404],
         [ 0.7191,  0.4450, -0.2955, -0.8187, -0.0228],
         [-0.9783,  0.0550, -0.9054,  1.8447, -1.3366]]])

### Module

Module can be used as a base class for creating neural networks, it offers some functionality which makes the job easier. For instance, when ever we call the object of our module `forward()` will be executed and the arguments will be pass on to that function

In [75]:
??torch.nn.Module

In [76]:
class PyModule(torch.nn.Module):
    def __init__(self, param1, param2, param3):
        super().__init__()
        self.param1 = torch.nn.Parameter(param1)
        self.param2 = torch.nn.Parameter(param2)
        self.param3 = param3
    
    def forward(self, inp):
        return self.param1 + self.param2 + self.param3 + inp

Module will only register as parameters only the argumets we set using `torch.nn.Parameter()` 

In [80]:
module = PyModule(tensor([1., 2., 3.]), tensor([1., 1., 1.]), tensor([1., 1., 1.]))
list(module.parameters())

[Parameter containing:
 tensor([1., 2., 3.], requires_grad=True),
 Parameter containing:
 tensor([1., 1., 1.], requires_grad=True)]

In [81]:
module(tensor([-1, -1, -1]))

tensor([2., 3., 4.], grad_fn=<AddBackward0>)

### Derivatives

In [2]:
def f(x):
    return (x)**2 + (3*x)

In [3]:

x1 = torch.tensor(2.).requires_grad_()
y1 = f(x1)
y1.backward()
x1.grad

tensor(7.)